import { Menu } from "@/types/Menu";

export const menuData: Menu[] = [
  {
    id: 1,
    title: "Women",
    newTab: false,
    path: "/shop-with-sidebar",
    hidden: false,
  },
  {
    id: 2,
    title: "Men",
    newTab: false,
    path: "/shop-with-sidebar",
    hidden: false,
  },
  {
    id: 3,
    title: "Kids",
    newTab: false,
    path: "/shop-with-sidebar",
    hidden: false,
  },
  {
    id: 4,
    title: "Accessories",
    newTab: false,
    path: "/shop-with-sidebar",
    hidden: false,
  },
  {
    id: 5,
    title: "Sale",
    newTab: false,
    path: "/shop-with-sidebar",
    hidden: false,
  },
  {
    id: 6,
    title: "Pages",
    newTab: false,
    path: "/",
    hidden: false,
    submenu: [
      {
        id: 61,
        title: "Shop With Sidebar",
        newTab: false,
        path: "/shop-with-sidebar",
        hidden: false,
      },
      {
        id: 62,
        title: "Shop Without Sidebar",
        newTab: false,
        path: "/shop-without-sidebar",
        hidden: false,
      },
      {
        id: 64,
        title: "Checkout",
        newTab: false,
        path: "/checkout",
        hidden: false,
      },
      {
        id: 65,
        title: "Cart",
        newTab: false,
        path: "/cart",
        hidden: false,
      },
      {
        id: 66,
        title: "Wishlist",
        newTab: false,
        path: "/wishlist",
        hidden: false,
      },
      {
        id: 67,
        title: "Sign in",
        newTab: false,
        path: "/signin",
        hidden: false,
      },
      {
        id: 68,
        title: "Sign up",
        newTab: false,
        path: "/signup",
        hidden: false,
      },
      {
        id: 69,
        title: "My Account",
        newTab: false,
        path: "/my-account",
        hidden: false,
      },
      {
        id: 70,
        title: "Contact",
        newTab: false,
        path: "/contact",
        hidden: false,
      },
      {
        id: 75,
        title: "Error",
        newTab: false,
        path: "/error",
        hidden: false,
      },
      {
        id: 63,
        title: "Mail Success",
        newTab: false,
        path: "/mail-success",
        hidden: false,
      },
    ],
  },
  {
    id: 7,
    title: "Blogs",
    newTab: false,
    path: "/",
    hidden: false,
    submenu: [
      {
        id: 71,
        title: "Blog Grid with sidebar",
        newTab: false,
        path: "/blogs/blog-grid-with-sidebar",
        hidden: false,
      },
      {
        id: 72,
        title: "Blog Grid",
        newTab: false,
        path: "/blogs/blog-grid",
        hidden: false,
      },
      {
        id: 73,
        title: "Blog details with sidebar",
        newTab: false,
        path: "/blogs/blog-details-with-sidebar",
        hidden: false,
      },
      {
        id: 74,
        title: "Blog details",
        newTab: false,
        path: "/blogs/blog-details",
        hidden: false,
      },
    ],
  },
];
